FactoryBot.define do
  factory :quiz do
    titolo "MyString"
    d1 "MyString"
    d2 "MyString"
    d3 "MyString"
    d4 "MyString"
    d5 "MyString"
    g1 "MyString"
    g2 "MyString"
    g3 "MyString"
    g4 "MyString"
    g5 "MyString"
    r1_1 "MyString"
    r1_2 "MyString"
    r1_3 "MyString"
    r2_1 "MyString"
    r2_2 "MyString"
    r2_3 "MyString"
    r3_1 "MyString"
    r3_2 "MyString"
    r3_3 "MyString"
    r4_1 "MyString"
    r4_2 "MyString"
    r4_3 "MyString"
    r5_1 "MyString"
    r5_2 "MyString"
    r5_3 "MyString"
    tutorial nil
  end
end
